import json
import os
import sys
from typing import Dict

# Import your global shared state schema
from state_schema import ClaimsState
# Import the custom SQL database calculator tool we built earlier
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
PARENT_DIR = os.path.abspath(os.path.join(CURRENT_DIR, ".."))
if PARENT_DIR not in sys.path:
    sys.path.append(PARENT_DIR)
BUDGET_DB_PATH = os.path.join(PARENT_DIR, "Data", "budget_databases", "budget_data.db")
from Tools.budget_calculator import calculate_repair_budget

def budget_agent(state: ClaimsState) -> Dict:
    """
    Budget Agent: Executes in parallel with the Policy Agent. It reads the 
    standardized damaged items and disaster severity, processes the metrics 
    via the local contractor database tool, and records the cost results.
    """

    print("\n==================================================")
    print("EXECUTING PARALLEL BUDGET CALCULATION NODE")
    print("==================================================")

    # 1. Input Phase: Fetch the structured output generated by the Reader Node
    extracted_claim_data = state.get("extracted_claim_data", {})
    
    # Safely extract the calculation keys with defensive programming fallbacks
    damaged_items = extracted_claim_data.get("damaged_items_or_areas", [])
    damage_severity = extracted_claim_data.get("damage_severity", "Medium")

    print(f" -> Input Received: Areas: {damaged_items} | Severity: {damage_severity}")

    # 2. Tool Phase: Execute the local contractor SQL pricing calculation tool
    # This runs with pure mathematical logic—zero network or token latency!
    calculation_report = calculate_repair_budget(
        damaged_areas=damaged_items, 
        severity=damage_severity
    )

    # 3. Output Phase: Format the payload to update the global shared state contract
    # The returned key directly updates 'calculated_budget' inside ClaimsState
    print("--------------------------------------------------")
    print(f"SUCCESS: Total Contractor Repair Budget = ${calculation_report.get('total_estimated_budget'):,.2f}")
    print("--------------------------------------------------")
    
    return {
        "calculated_budget": calculation_report
    }
"""
if __name__ == "__main__":
    # Example test case for local debugging
    test_state = ClaimsState(
        client_phone_number="+918333444555",
        raw_user_input="",
        extracted_claim_data={
            "client_name": "Suresh Kumar",
            "disaster_type": "Flood",
            "damage_severity": "High",
            "damaged_items_or_areas": ["flooring", "drywall"],
            "estimated_impact_description": "Water tracking ruined structural lower segments."
        }
    )
    
    result = budget_agent(test_state)
    print(json.dumps(result, indent=2))
"""