import os
import json
import sys
from typing import Dict
from google import genai
from google.genai import types
from dotenv import load_dotenv


# Import the shared state schema and your validation tool function
from state_schema import ClaimsState

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
PARENT_DIR = os.path.abspath(os.path.join(CURRENT_DIR, ".."))
if PARENT_DIR not in sys.path:
    sys.path.append(PARENT_DIR)
from Tools.client_validation_tool import verify_client_registration

load_dotenv()
client = genai.Client(api_key=os.getenv("GOOGLE_API_KEY"))

def planner_agent(state: ClaimsState) -> Dict:
    """
    Main central agent acting as the system orchestrator.
    Optimized for strict token efficiency and tool-driven gatekeeping.
    """
    # Extract existing state variables
    raw_user_input = state.get("raw_user_input", "")
    client_phone_number = state.get("client_phone_number", "")
    extracted_claim_data = state.get("extracted_claim_data", {})
    policy_analysis = state.get("policy_analysis", {})
    calculated_budget = state.get("calculated_budget", {})
    drafted_offer = state.get("drafted_offer", {})
    final_summary=state.get("executive_summary", "")

    # ==============================================================================
    # 🛡️ PHASE 0: ENTRANCE VERIFICATION & SECURITY GATEKEEPER
    # ==============================================================================
    if not policy_analysis:
        print(f"🛰️ [PLANNER INITIALIZATION] Invoking client validation tool for: {client_phone_number}")
        validation_result = verify_client_registration(client_phone_number)
        
        # If the verification tool returns unregistered, break immediately
        if validation_result.get("policy_name") == "UNREGISTERED_CLIENT":
            print("🛑 [ORCHESTRATOR ALERT] Unregistered client attempt. Short-circuiting graph loops.")
            return {
                "policy_analysis": {
                    "status": "VIOLATE",
                    "policy_name": "UNREGISTERED_CLIENT",
                    "reason": "Tracking signature missing from registration records."
                }
            }
        
        # If verified successfully, seed the state with the baseline PENDING data block
        policy_analysis = validation_result

    # 🛑 If already flagged as unregistered in a previous pass, don't allow processing
    if policy_analysis.get("policy_name") == "UNREGISTERED_CLIENT":
        return {"policy_analysis": policy_analysis}

    # ==============================================================================
    # 🔀 PHASE 1 & 2: RE-ROUTING (Bypass LLM compilation if steps are running)
    # ==============================================================================
    if not extracted_claim_data or (policy_analysis.get("status") == "PENDING" or not calculated_budget):
        return {
            "raw_user_input": raw_user_input,
            "client_phone_number": client_phone_number,
            "extracted_claim_data": extracted_claim_data,
            "policy_analysis": policy_analysis,
            "calculated_budget": calculated_budget
        }
    if ((policy_analysis.get("status") == "VIOLATE") or (policy_analysis.get("status") == "OK")) and not drafted_offer:
        return{
            "drafted_offer": drafted_offer
        }
    
    # ==============================================================================
    # 🏁 PHASE 4: FINAL SYNTHESIS REPORT (Triggered once components settle)
    # ==============================================================================

    if drafted_offer and not final_summary:
        
        # 1. Stripped-down, high-impact System Instruction
        planner_instruction = """
            You are the central orchestrator for an emergency insurance claims system.
            Your task is to compile a definitive, executive-ready final summary report by
            synthesizing the raw claim and the analytical outputs generated by specialized worker nodes.
        """

        # 2. Compacted Prompt Template (Removed all decorative lines and verbose phrasing)
        prompt_template = f"""
            Context Data:
            - Phone Number: {client_phone_number}
            - Raw Claim: {raw_user_input}
            - Extracted Info: {json.dumps(extracted_claim_data)}
            - Policy Status: {json.dumps(policy_analysis)}
            - Calculated Budget: {json.dumps(calculated_budget)}
            - Resolution Data: {json.dumps(drafted_offer if drafted_offer else policy_analysis)}

            Task:
                Synthesize the context data above into a clean, professional claims summary report. 
                Do not include internal execution logs, reasoning steps, or conversational filler text.
                The final output should be a concise, well-structured report suitable for executive review.
            """
        
        # 3. Gemini API Invocation
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt_template,
            config=types.GenerateContentConfig(
                system_instruction=planner_instruction,
                temperature=0.0,
            ),
        )
        return {"executive_summary": response.text}
    return {}
